# Generated by Django 3.1.3 on 2021-01-15 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('strassenNr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plz', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cronjob.address')),
            ],
        ),
        migrations.CreateModel(
            name='Cronjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('notification', models.CharField(max_length=45)),
                ('minute', models.CharField(max_length=45)),
                ('hour', models.CharField(max_length=45)),
                ('weekday', models.CharField(max_length=45)),
                ('month', models.CharField(max_length=45)),
                ('day', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cronjob.user')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='plz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cronjob.ort'),
        ),
    ]
